# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Reed Kinning's Interactive Portfolio
email: reed.kinning@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Intended for employers and curious individuals.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reedkinning.com" # the base hostname & protocol for your site
github_username:  rk23

# Build settings
markdown: kramdown
